### PR TITLE
Availability support

### PR DESCRIPTION
**Pull request by typfel**
## What's new
Re-generated proto buffer classes with availability definition.

### CODE REVIEW

**Comment by mikeger** [comment]
We picked up now quite some changes that where not anticipated for availability:
1. Encryption type.
2. Asset source / caption.
3. Multiple confirmation.

What is the impact on the wire-ios source code from those additional changes (for example message_id was removed from delivery)? What is the impact for the compatibility with the other platforms?

**Comment by typfel** [comment]
@mikeger the only change this means for is is that `ZMConfirmation.messageId` has changed to `ZMConfirmation.firstMessageId`

**Comment by mikeger** [comment]
I guess in the future we can start confirming multiple messages with one confirmation? Is web already doing it?

**Comment by typfel** [comment]
Probably not since all clients would need to support it.

**Pull request merged**
