### PR TITLE
Update generic message protobuf to 1.24

### PR DESCRIPTION
**Pull request by typfel**
## What's new in this PR?

Update generic message protobuf to 1.24

### CODE REVIEW

**Comment by vytis** [comment]
Would also be good to regenerate the Swift-based code

**Comment by alexaubry** [comment]
@typfel Do we also need to get this in? https://github.com/wireapp/generic-message-proto/pull/47

**Comment by typfel** [comment]
@alexaubry yes, but I figured we can just bump it again later

**Comment by typfel** [comment]
@zenkins release minor

**Pull request merged**
