### PR TITLE
[Refactor] Remove Messages.pb 

### PR DESCRIPTION
**Pull request by David-Henner**
## What's new in this PR?

Removed:
- Messages.pb.m 
- Messages.pb.h

## note

will merge once changes have been tested

### CODE REVIEW

**Comment by typfel** [comment]
We can also remove:

- `github "wireapp/protobuf-objc" ~> 1.9` from the Cartfile
- `compile-protos.sh` from the Scripts folders

**Comment by typfel** [comment]
And what about `Otr.pb.m` `Otr.pb.h` I guess we can remove those as well?

**Comment by David-Henner** [comment]
> And what about `Otr.pb.m` `Otr.pb.h` I guess we can remove those as well?

Not sure wether they were taken into account in the refactoring, as main focus was on `ZMGenericMessage`.
I will check if it can be removed safely.

**Comment by KaterinaWire** [comment]
@zenkins release major

**Pull request merged**
